# Generated by Django 3.0.6 on 2021-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('idd', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('mark', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='mark')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('roll_no', models.CharField(max_length=200, unique=True, verbose_name='Roll Number')),
                ('dob', models.DateField(verbose_name='date of birth')),
            ],
        ),
    ]
