# Generated by Django 3.0.6 on 2021-09-21 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210919_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, message='above %(limit_value)s.'), django.core.validators.MinValueValidator(0, message='not below %(limit_value)s')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth (yyyy-mm-dd)'),
        ),
    ]
