# Generated by Django 3.0.6 on 2021-09-21 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210921_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='New Mark'),
        ),
    ]
